carlo comments on MASP + Multisig veification
anoma/namada-docs pull request #137
Opened 2023-09-08 17:02 UTC by CarloModicaPortfolio

2023-09-11 09:27 UTC, cwgoes commented
cc @bengtlofgren

2023-09-12 11:56 UTC, bengtlofgren requested changes

2023-09-18 10:52 UTC, bengtlofgren approved these changes

2023-09-18 11:04 UTC, bengtlofgren requested changes

2023-09-18 11:04 UTC, bengtlofgren commented on packages/specs/pages/masp/burn-and-mint.mdx
> +It be easier for the reader if these values contained in the public and private input where defined
@CarloModicaPortfolio

2023-09-18 11:04 UTC, bengtlofgren commented on packages/specs/pages/masp/storage-interface.mdx
> +1. How is the count query related to the stopping of the scanning?
```suggestion
```

I don't know the answer to this question. @murisi

2023-09-18 11:04 UTC, bengtlofgren commented on packages/specs/pages/masp/storage-interface.mdx
> +1. What value?
The value in the hash-map like structure (hence key and value tor refer).
```suggestion
```

2023-09-18 11:04 UTC, bengtlofgren commented on packages/specs/pages/masp/masp-vp.mdx
> +2. why are we using the word "descriptions" here? What is it? Which one are we of the two are we going to unpack?
```suggestion

```

2023-09-18 11:04 UTC, bengtlofgren commented on packages/specs/pages/masp/masp-vp.mdx
> +2. why are we using the word "descriptions" here? What is it? Which one are we of the two are we going to unpack?
I don't know what we want to replace this with. I have no valid definition for the 'host environment' @cwgoes ?
@CarloModicaPortfolio What do you mean by "Which one of the two are we going to unpack?" -- Which two?

2024-02-13 17:13 UTC, closed without merging