update indexer docs
anoma/namada-docs pull request #373
Opened 2024-08-07 18:56 UTC by iskay

since namadexer is no longer maintained,
- replaced contents of 'using the indexer' section with heliax namada-indexer
- moved namadexer to a new page marked as deprecated

2024-08-07 18:56 UTC, iskay commented
or should we just remove namadexer section entirely?

2024-08-07 21:02 UTC, Fraccaman commented
we can leave namadexer, but we should also mention about undexer (just a link to their repo is fine)

2024-08-07 21:21 UTC, brentstone requested changes
LGTM, let's just consider Gian's comment about mentioning and linking to the undexer then good to merge

2024-08-08 21:21 UTC, brentstone approved these changes

2024-08-08 21:21 UTC, merged