refactored governance specs
anoma/namada-docs pull request #75
Opened 2023-07-03 14:48 UTC by bengtlofgren

2023-07-06 10:01 UTC, cwgoes requested changes
See comments. I like the separation of the storage keys part!

2023-07-06 10:01 UTC, cwgoes commented on packages/specs/pages/governance/proposal.mdx
> +`ETHBridge` is aimed at regulating actions on the bridge like the update of the Ethereum smart contracts or the withdrawing of all the funds from the `Vault` :
aren't we ditching this one?

2023-07-06 10:03 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +It is possible to check the actual implementation [here](https://github.com/anoma/namada/blob/main/shared/src/ledger/governance/mod.rs#L69)
Good point

2023-07-06 10:04 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +If only validators are allowed to vote for the `ProposalType` in exam, they are allowed to vote for the entire voting window.
Good point, I think I meant in question lmao

2023-07-06 10:05 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +At the beginning of each new epoch (and only then), in the `finalize_block` function, tallying will occur for all the proposals that have a `grace_epoch` matching the current epoch.
No, the counting happens at grace epoch. I'll see if this can be made more clear

2023-07-06 10:06 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +E.g if the threshold is $\frac{1}{2}$, then at least 50% of the total staked `NAM` must have voted `Yay` for the proposal to be accepted.
That would probably be a more efficient way of checking

2023-07-06 10:07 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +It is possible to check the actual implementation [here](https://github.com/anoma/namada/blob/main/shared/src/ledger/governance/utils.rs#L68).
```suggestion
```

2023-07-06 10:07 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +The correct logic to handle these different types will be hardcoded in protocol.
```suggestion
The correct logic to handle these different types is hardcoded in protocol. 
```

2023-07-06 10:08 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +It is possible to check the actual implementation [here](https://github.com/anoma/namada/blob/main/shared/src/ledger/governance/mod.rs#L69)
```suggestion

```

2023-07-06 10:10 UTC, bengtlofgren commented on packages/specs/pages/governance/proposal.mdx
> +    Acronym **NIP** == Namada Improvement Proposal
But ... there are jokes to be made here 🙊 

Sure, proposals it is

2023-07-06 10:10 UTC, bengtlofgren commented on packages/specs/pages/governance/proposal.mdx
> +`ETHBridge` is aimed at regulating actions on the bridge like the update of the Ethereum smart contracts or the withdrawing of all the funds from the `Vault` :
This is true

2023-07-06 10:27 UTC, bengtlofgren commented on packages/specs/pages/governance/on-chain.mdx
> +At the beginning of each new epoch (and only then), in the `finalize_block` function, tallying will occur for all the proposals that have a `grace_epoch` matching the current epoch.
Hopefully more clear now

2023-07-24 13:11 UTC, cwgoes approved these changes

2023-07-24 13:21 UTC, merged